call plug#begin()
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
Plug 'AndrewRadev/splitjoin.vim'
Plug 'SirVer/ultisnips'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'Tagbar'
Plug 'scrooloose/nerdtree'
call plug#end()
"set clipboard+=unnamed
"autocmd vimenter * NERDTree

"set tagbar windows kuaidu
let g:tagbar_width=30
map <F6> :TagbarToggle<CR>
map <F7> :NERDTreeToggle<CR>
let g:go_highlight_types = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4 
let g:go_fmt_command = "goimports"
